apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx9
  template:
    metadata:
      labels:
        app: nginx9
    spec:
      containers:
      - name: nginx9
        image: nginx:latest
        ports:
        - containerPort: 80

