apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx8
  template:
    metadata:
      labels:
        app: nginx8
    spec:
      containers:
      - name: nginx8
        image: nginx:latest
        ports:
        - containerPort: 80

